version: '2'

networks:
  nexus:
    driver: bridge
  install:
    driver: bridge
volumes:
  nexus:
# 初始账号的账号密码分别是admin和admin123
services:
  nexus:
    image: 'sonatype/docker-nexus3'
    restart: always
    container_name: nexus
    environment: 
      JAVA_MAX_MEM: 768m
    ports:
      - '8081:8081'
    volumes:
      - 'nexus:/nexus-data'
      - 'install:/opt/sonatype/nexus'

