version: '2'

volumes:
  nexus:
# 初始账号的账号密码分别是admin和admin123
services:
  nexus:
    image: 'sonatype/nexus3:latest'
    restart: always
    container_name: nexus
    environment: 
      JAVA_MAX_MEM: 768m
    ports:
      - '8081:8081'
    volumes:
      - 'nexus:/nexus-data'