version: '2'

volumes:
  nexus:

# login name: admin
# login password: admin123
services:
  nexus:
    image: 'sonatype/nexus3:latest'
    restart: always
    container_name: nexus
    environment: 
      JAVA_MAX_MEM: 768m
    ports:
      - '8081:8081'
    volumes:
      - 'nexus:/nexus-data'