version: '3.1'

volumes:
  neo4j_data: 

services:
  
  neo4j:
    image: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - "neo4j_data:/data"