version: '3'
services:
  sonarqube:
    image: sonarqube:alpine
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      # database info
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://localhost/sonar