version: '2'
volumes:
  db-data:
  sonar-data:
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    expose:
      - "5432"

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    volumes:
      - sonar-data:/opt/sonarqube/data
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    ports:
      - "9000:9000"
    links:
      - postgres