version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/log/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    expose:
      - "5432"

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    ports:
      - "9000:9000"
    links:
      - postgres