version: '3.7'

services: 
    teamcity:
        image: jetbrains/teamcity-server:2019.2.2
        container_name: teamcity
        restart: always
        ports: 
            - 8111:8111
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8111/ping || exit 1"]
        volumes: 
            - "./data:/data/teamcity_server/datadir"
            - "./logs:/opt/teamcity/logs"
            # sync the time
            - "/etc/localtime:/etc/localtime:ro"