FROM debian:stable-slim
LABEL maintainer="alexcdever@gmail.com"
WORKDIR /root

RUN apt update -y \
    && apt upgrade -y \
    && apt install locales-all zsh git   -y —no-install-recommends\
    && apt-get purge -y —auto-remove $fetchDeps \
    && rm -rf /var/lib/apt/lists/*
