version: '3.7'

networks:
  traefik:

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0.4
    restart: always
    container_name: traefik
    networks:
      - traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI
      - "8080:8080"
      - "443:443"
    expose:
      - 8080
    environment:
      # DNSPOD
      - DNSPOD_API_KEY=
      # CLOUDFLARE
      - CF_API_EMAIL=alexcdever@gmail.com
      - CF_API_KEY=
      - CF_DNS_API_TOKEN=

    volumes:
      # docker
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # config
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic.yml:/etc/traefik/dynamic.d/dynamic.yml"
      # log
      - "./log:/data/traefik/log/"
      # https
      - "./ca/:/data/traefik/ca/"