version: '3.7'
networks:
   mssql:
     driver: bridge
volumes:
  mssql: 
services:
  mssql: 
    image: microsoft/mssql-server-linux
    container_name: mssql
    privileged: true
    restart: always
    ports: 
      - "1433:1433"
    networks:
      - mssql
    expose:
      - "3306"
    volumes:
      - "mssql:/var/opt/mssql"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=G1veMeP@ss
      