version: '3'

networks:
   CI:
     driver: bridge

volumes:
  db:
  gitlab_config:
  gitlab_log:
  gitlab_data:

services:
  gitlab:
    image: 'beginor/gitlab-ce:11.1.4-ce.0'
    restart: always
    hostname: 'gitlab.alexc.cn'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8080:80'
      - '8443:443'
      - '822:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_log:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'

