version: '3.1'

networks:
  mysql:
volumes:
  data:
  conf:
services:
  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    networks: 
      - "mysql"
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - conf:/etc/mysql/mysql.conf.d
    environment:
      #管理员root的密码
      MYSQL_ROOT_PASSWORD: "root"