version: '3.7'

networks: 
    redis:
        name: redis

volumes: 
    data:

services:
    redis:
        image: redis:5.0-alpine
        container_name: redis
        networks: 
            - redis
        ports: 
            - 8111:8111
        volumes: 
            - "data:/data"
            - "./config:/usr/local/etc/redis"